### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by jasonvarga**
Hey Max, try out these changes. It should make things simpler. You shouldn't need to use those service classes yourself.

### CODE REVIEW

**Comment by mwesten** [comment]
Hi Jason,

Looks great, but unfortunately doesn't work all the way...
When in default language(en) it shows the link for the dutch(nl) language just fine.
When on the dutch page, the function `Content::whereUri($url)` returns a `null` value, and thus throwing a Fatal error.

**Comment by jasonvarga** [comment]
Updated.

**Comment by mwesten** [comment]
Hmmmm that doesn't work either....
This just returns the root url for every page.

This works however:
`$uri = URL::unlocalize($url, site_locale());` instead of `$uri = URL::getDefaultUri($url, site_locale());`

BTW: you're fast :)

**Comment by jasonvarga** [comment]
Updated again. I had the arguments backwards :(
That's what I get for editing directly on Github.

**Pull request merged**
